site_name: Multiple Sclerose (MS)

nav:
  - Home: index.md
  - Informatie:
    - Het gezonde zenuwstelsel: gezonde_zenuwstelsel.md
    - Wat is MS?: MS.md

  - Ziektebeeld: 
    - Verschillende vormen: vormen.md
    - Symptomen: symptomen.md
    - Diagnose: diagnose.md
    - Behandeling: behandeling.md

  - Immuunsysteem:
    - B-lymfocyten: b_lymfocyten.md
    - T-lymfocyten: t_lymfocyten.md
    - Overige celtypen: overig_cel.md

  - Quiz: quiz.md

plugins:
  - search

site_dir: site

  
